### ISSUE TITLE
As mytiki.com, I want to deploy a centralized writer, so that customer lakes meet the iceberg spec.

### ISSUE THREAD

**Issue by mike-audi** [tiki/ocean-metadata#106]
### Acceptance Criteria

- [ ] A deployable metadata writer
- [ ] A metadata queue
- [ ] Support multiple lakes
- [ ] A SAR application to deploy the catalog in any mytiki account

### Tasks

- [ ] move to private repo in tiki
- [ ] CF template for queue and writer
- [ ] SAR application with org visibility
- [ ] Update writer to support N lakes
