### ISSUE TITLE
As mytiki.com, I want to design an API, so that customer lake writes trigger metadata writes

### ISSUE THREAD

**Issue by mike-audi** [tiki/ocean-metadata#107]
### Acceptance Criteria

- [ ] a metadata event appears in the metadata sqs queue when data is added to a customer lake
- [ ] the metadata file in the corresponding lake directory is updated by the writer

### Tasks

- [ ] investigate: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-cross-account.html
- [ ] investigate a REST API
